version: "3"
services: 
  nginx:
    image: nginx:stable-alpine
    ports: 
      - "3000:80"
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    image: josep9515/node-app
    environment: 
      - PORT=3000
    depends_on: 
      - mongo
    
  mongo:
    image: mongo
    environment: 
        - MONGO_INITDB_ROOT_USERNAME=josep.andreu%40e-campus.uab.cat
        - MONGO_INITDB_ROOT_PASSWORD=celdoni
    volumes: 
      - mongo-db:/data/db 

  redis: 
    image: redis
    

volumes: 
  mongo-db:



 # docker-compose up -d for using docker-compose for buiding the image