version: "3"
services: 
  node-app:
    build: .
    ports: 
      - "3000:3000"
    volumes: 
      - ./:/app
      - /app/node_modules
    environment: 
      - PORT=3000
    # env_file: use ife there are more than one enviorment variables
    #  - ./.env 

# docker-compose up -d for using docker-compose for buiding the image
